# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

warnings_are_errors: true
cache: packages

before_script:
  - Rscript -e 'tinytex::install_tinytex()'
  - Rscript -e 'tinytex::tlmgr_install(pkgs = c("booktabs", "longtable", "array", "multirow", "wrapfig", "float", "colortbl", "pdflscape", "tabu", "threeparttable", "threeparttablex", "makecell", "graphicx"))'

after_success:
  - Rscript -e 'covr::codecov()'

