# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

os:
  - linux

r:
  - release

warnings_are_errors: true
sudo: required
cache: packages
group: deprecated-2017Q4

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'

